### 인공신경망 이론
#### 인공 뉴런

In [3]:
# AND 연산
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))
b = 2 
out = 1 if x1 + x2 >= b else 0
print('뉴런 출력:', out)
#1, 1 : 1 / 0, 1 : 0 / 1, 0 : 0 / 0, 0 : 0

입력(콤마로 구분하여 입력하시오): 0,0
뉴런 출력: 0


In [5]:
# OR 연산
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))
b = 1 
out = 1 if x1 + x2 >= b else 0
print('뉴런 출력:', out)
#1, 1 : 1 / 0, 1 : 1 / 1, 0 : 1 / 0, 0 : 0

입력(콤마로 구분하여 입력하시오): 0, 1
뉴런 출력: 1


### 헵의 학습이론
- 학습이 이루어지면 시냅스가 강화
- 시냅스의 변화를 가중치로 모델링

#### 헵의 인공 신경 세포

In [5]:
# AND 연산
#퍼셉트론 구현
#구조 : 입력노드 2개, 출력층 노드 1개
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))

b = -0.5
w1 = 0.38
w2 = 0.42
y = x1 * w1 + x2 * w2 + b

out = 1 if y >= 0.0 else 0

print('뉴런 출력:', out)
#0, 0: 0 / 0, 1 : 0 / 1, 0 : 0 / 1, 1 : 1

입력(콤마로 구분하여 입력하시오): 0, 1
뉴런 출력: 1


In [8]:
# OR 연산
#퍼셉트론 구현
#구조 : 입력노드 2개, 출력층 노드 1개
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))

b = -0.01
w1 = 0.36
w2 = 0.39
y = x1 * w1 + x2 * w2 + b

out = 1 if y >= 0.0 else 0

print('뉴런 출력:', out)
#0, 0: 0 / 0, 1 : 1 / 1, 0 : 1 / 1, 1 : 1

입력(콤마로 구분하여 입력하시오): 0, 1
뉴런 출력: 1


In [9]:
#Numpy로 구현한 AND 연산 신경세포
import numpy as np

x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))
X = np.array([x1, x2])

b = -0.5
w1 = 0.38
w2 = 0.42
W = np.array([w1, w2]).reshape(-1, 1)

y = np.dot(X, W) + b

out = 1 if y >= 0.0 else 0

print('뉴런 출력:', out)
#0, 0: 0 / 0, 1 : 0 / 1, 0 : 0 / 1, 1 : 1

입력(콤마로 구분하여 입력하시오): 0, 1
뉴런 출력: 0


In [8]:
# OR 연산
#퍼셉트론 구현
#구조 : 입력노드 2개, 출력층 노드 1개
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))

b = -0.01
w1 = 0.36
w2 = 0.39
y = x1 * w1 + x2 * w2 + b

out = 1 if y >= 0.0 else 0

print('뉴런 출력:', out)
#0, 0: 0 / 0, 1 : 1 / 1, 0 : 1 / 1, 1 : 1

입력(콤마로 구분하여 입력하시오): 0, 1
뉴런 출력: 1


#### Perceptron 학습 규칙 (델타 룰)
- 경사하강법, 해석적 미분법
- 비용함수(Cost함수/loss함수) : 에러가 최소일 때, 최소값을 가지는 함수
- SE: 비용오차

In [13]:
# OR 연산
#Delta_w 구하기
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
t = np.array([0., 1., 1., 1.]).reshape(-1,1) #target

b = -0.01
w1 = 0.36
w2 = 0.39
W = np.array([w1, w2]).reshape(-1, 1)

y = np.dot(X, W) + b

print('y:\n', y, y.shape)

out = np.zeros_like(y)
out = (y >= 0.0).astype(float) #step function
print('out:\n', out)

y:
 [[-0.01]
 [ 0.38]
 [ 0.35]
 [ 0.74]] (4, 1)
out:
 [[0.]
 [1.]
 [1.]
 [1.]]


In [14]:
e = t - y #e : error
print('error:\n', e)

d_w2 = np.dot(X.T, e)
print('d_w2:\n', d_w2)

error:
 [[0.01]
 [0.62]
 [0.65]
 [0.26]]
d_w2:
 [[0.91]
 [0.88]]


In [15]:
def stepfunc(x):
    return (x >= 0.0).astype(float)

In [20]:
class Perceptron:
    def __init__(self, x, y):
        self.input = x
        #self.w = np.zeros((self.input.shape[1], 1))
        self.w = np.random.rand(self.input.shape[1], 1)
        self.t = y
        self.output = np.zeros_like(self.t)
    
    def feedforward(self):
        self.output = stepfunc(np.dot(self.input, self.w))

    def train(self, eta):
        d_w = np.dot(self.input.T, eta*(self.t - self.output)) #내적 결과
        #update the weights
        self.w += d_w    

In [21]:
# 논리-AND를 수행하는 퍼셉트론 ,
# the third input is for bias
X = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[0],[0],[1]])
nn = Perceptron(X, y)

for i in range(1500): #epoch 1500번
    nn.feedforward()
    nn.train(0.01)

print('output:\n', nn.output)
print('weights:\n', nn.w)

output:
 [[0.]
 [0.]
 [0.]
 [1.]]
weights:
 [[ 0.31845932]
 [ 0.01047849]
 [-0.32578564]]


In [22]:
# 논리-OR를 수행하는 퍼셉트론 ,
# the third input is for bias
X = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[1],[1],[1]])
nn = Perceptron(X, y)

for i in range(1500): #epoch 1500번
    nn.feedforward()
    nn.train(0.01)

print('output:\n', nn.output)
print('weights:\n', nn.w)

output:
 [[0.]
 [1.]
 [1.]
 [1.]]
weights:
 [[ 0.98087609]
 [ 0.91674606]
 [-0.00279313]]


### SLP 퍼셉트론의 한계점 및 해결 방안
#### 마빈 민스키 & 세이무어 페퍼트
- 퍼셉트론 이론의 한계점 증명
- 논리-XOR 연산을 수행하지 못함

In [23]:
# XOR 문제
# the third input is for bias
X = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[1],[1],[0]])
nn = Perceptron(X, y)

for i in range(1500): #epoch 1500번
    nn.feedforward()
    nn.train(0.01)

print('output:\n', nn.output)
print('weights:\n', nn.w)

output:
 [[1.]
 [1.]
 [1.]
 [1.]]
weights:
 [[ 0.00412263]
 [ 0.00047972]
 [-0.01690518]]


### 해결방안 : Multi layered Perceptron(다층 신경망)
- 다층퍼셉트론
- 폴 워보스가 다층 신경망을 제안하고 학습 알고리즘으로 역전파 알고리즘 고안
- -> 딥러닝의 이론이 됨

#### 학습 규칙 : 역전파 학습(EBP, Error Back Propagation)