# NumPy
### import numpy as np
- 파이썬 라이브러리
- 행렬이나 대규모 다차원 배열을 쉽게 처리
- 배열에는 모두 동일한 자료형만 저장
- 메모리에 연속적으로 저장

## 배열의 생성

In [1]:
import numpy as np

In [3]:
ar = np.array([1,2,3,4,5])
ar

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array(range(1, 6))
arr

array([1, 2, 3, 4, 5])

In [7]:
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]]) #2차원 배열
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
ar3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]) #3차원 배열
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
[10,8,15,7,19]

In [ ]:
[10, 20, 30], [40, 50, 60], [70, 80, 90]

## 배열관련 주요 함수
### 객체변수처럼 사용 가능 (ex. ar.ndim / ar.shape)
- shape: 배열의 형태 반환 / 행렬의 모양을 확인
- reshape: 배열의 형태 변환 / 행렬의 모양을 변경
- ndim: 배열의 차원 반환 / 행렬의 차수(깊이)를 확인
- len : 길이를 확인
- type : 형식을 확인
- T: 행, 열 전환
- Slicing: 특정 열이나 행을 선택하여 추출
- np.ones : 행렬을 1로 채워줌
- np.ones_like : 대상과 같은 shape의 행렬을 1로 채워줌
- np.zeros : 행렬을 0으로 채워줌
- np.zeros_like : 대상과 같은 shape의 행렬을 0으로 채워줌
- np.arange : 배열 생성하기
- np.newaxis: 차원 확장
- np.vstack: 수직으로 쌓음
- np.hstack: 수평적으로 병합


In [9]:
type(arr)

numpy.ndarray

In [12]:
ar2.ndim
ar2.shape

(3, 3)

In [13]:
ar3.shape[0]

2

In [15]:
len(ar3[0][1])

3

In [16]:
np.ones((3,6)) #3행 6열

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
ar = np.arange(100, 110).reshape(2, 5)
ar

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

In [22]:
A = np.arange(0, 31, 2).reshape(4, 4) #(시작값, 끝값, step)
A

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [23]:
B = np.arange(1, 32, 2).reshape(4, 4)
B

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [24]:
C = np.arange(2, 33, 2).reshape(4, 4)
C

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [25]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
b = a.reshape(5, -1) #-1: 자동완성
c = a.reshape(-1, 2)
b, c

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]),
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]))

In [30]:
a[:, np.newaxis] #차원확장1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [36]:
a.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [37]:
a[np.newaxis, :] #차원확장2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [42]:
a.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

#### Transpose(T)
- 행과 열을 교체

In [40]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
np.arange(10).reshape(2, 5).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### Slicing(슬라이싱)
- 1차원 배열: 리스트와 동일
- 2차원 배열 : ','로 구별하여 연결

In [52]:
ar = np.arange(0, 12).reshape(3, 4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
ar[0:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [50]:
ar[1:, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [53]:
ar[1:2, 1:2][0]

array([5])

In [55]:
A = np.arange(1, 101).reshape(10, 10)
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [57]:
A[[1,3], :]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

### Concatenation(병합)
- np.vstack : 수직으로 쌓음
- np.hstack : 수평으로 병합

In [63]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], 
                 [6, 5, 4]]) #vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [60]:
#horizontally stack the arrays
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## 벡터화 계산 
- 원소 하나 하나씩 계산하는 것이 아니라 배열 단위로 계산
- loops 없이 연산하여 코딩의 양이 줄어듦
- 병렬처리 가능
#### 브로드캐스팅(broadcasting): 행렬끼리 연산할 때 크기가 다른 경우 이를 알아서 확대 해주는 기능
- Filtering

#### 사칙연산 모두 가능
- 덧셈, 뺄셈, 곱셈, 나눗셈

#### 논리연산과 비교연산 가능
- , >, <, ==, !=

#### 지수함수, 로그함수 지원
- Exp, **, log()

In [65]:
c = np.array([7,5,9,10,4,10,6,2]).reshape(2, 4)
c

array([[ 7,  5,  9, 10],
       [ 4, 10,  6,  2]])

In [66]:
d = np.array([1,3,4,9, 14,7,6,4]).reshape(2, 4)
d

array([[ 1,  3,  4,  9],
       [14,  7,  6,  4]])

In [67]:
c -d

array([[  6,   2,   5,   1],
       [-10,   3,   0,  -2]])

In [68]:
(c -d) > 0

array([[ True,  True,  True,  True],
       [False,  True, False, False]])

### 수행시간 비교
- 정수 리스트 2개, 각 원소를 곱하는 연산 수행
- %%time을 사용하여 수행시간을 확인

In [71]:
%%time
#수행시간이 얼마나 걸리는지 확인, %%time은 항상 첫 줄 + 같은줄에 주석 불가
datanum = 1000000
a = list(range(datanum))
b = list(range(datanum))
c = []
for i in range(datanum):
    c.append(a[i] * b[i])

CPU times: total: 234 ms
Wall time: 232 ms


In [72]:
%%time
datanum = 1000000
a = np.arange(datanum)
b = np.arange(datanum)
c = a * b

CPU times: total: 31.2 ms
Wall time: 31.9 ms


In [73]:
#broadcasting
a = np.arange(15).reshape(5, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [74]:
b = np.arange(5).reshape(5, 1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [75]:
c = a + b
c

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

### Filter

In [76]:
X = A < 10
print(X)

[[ True  True  True  True  True  True  True  True  True False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [77]:
A[X] = 0 #A에서 True인 부분만 잘라서 0대입
print(A) #배열을 print로 출력하면 ,(콤마) 안나옴

[[  0   0   0   0   0   0   0   0   0  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


## 배열 생성(추가) & random 배열 생성
- np.linspace : 주어진 범위를 개수만큼 분할
- np.logspace
- np.random.randint
- np.random.randn
- np.random.sample
- np.random.ranm()

In [2]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [3]:
np.random.random((2, 5, 3)) #3차원 shape(2, 5, 3) #0.0~9.9999 사이값

array([[[0.41218004, 0.51860268, 0.45472334],
        [0.38332309, 0.8296751 , 0.43992853],
        [0.90471267, 0.33081251, 0.52570247],
        [0.43520215, 0.45907194, 0.26812464],
        [0.37348802, 0.9767765 , 0.79084359]],

       [[0.89369946, 0.2367253 , 0.98420358],
        [0.34351709, 0.56512737, 0.97146093],
        [0.17840338, 0.50252658, 0.17720084],
        [0.44933843, 0.37680774, 0.12173044],
        [0.40727947, 0.27745667, 0.45231754]]])

In [6]:
np.random.randint(1, 10, 9)      #첫값, 끝값, 개수      #끝값 - 1까지 나옴

array([1, 4, 8, 2, 4, 3, 1, 1, 7])

In [8]:
np.random.rand(6) #-4.0 ~ +4.0 사이의 값

array([0.48546941, 0.41735235, 0.42595082, 0.4421094 , 0.04840525,
       0.46175547])

In [9]:
np.random.sample((3, 4))

array([[0.86762963, 0.16904375, 0.00986886, 0.76939977],
       [0.15704702, 0.38013524, 0.43193474, 0.04188696],
       [0.18567326, 0.70207775, 0.74097017, 0.38318288]])

### astype
- 배열.astype(datatype)
- 데이터 타입을 전부 바꿔주는 명령어

In [11]:
B = np.array([47, 85, 15, 33, 24])
B.astype(float)

array([47., 85., 15., 33., 24.])

In [14]:
D = np.array([1, 0, 1, 0, 0]).astype(bool)
D

array([ True, False,  True, False, False])

## 내적
- 가중치 합 (Weighted Sum) - 딥러닝 : 중요도에 따라 가중값을 곱해준 후 합산
- 가중치 평균 (Weighted average) : 각각의 가중치를 곱한 합을 전체 가중치의 합으로 나누기
- 유사도 검사 (Similarity check) - 자연어처리 등

### dot
- 두 행렬의 벡터 내적
- 1. np.dot(ar1, ar2)
- 2. a@b

In [18]:
np.array([1, 2, 3]) @ np.array([1, 2, 3]).T

14

In [17]:
a = np.array([3, 2, -1, 0, 2, 4]).reshape(2, 3)
b = np.array([2, 2, 3, 4, 5, 1]).reshape(3, 2)
a @ b #내적1

array([[ 7, 13],
       [26, 12]])

In [19]:
np.dot(a, b) #내적2

array([[ 7, 13],
       [26, 12]])

In [24]:
# 과일 구입 총액
f=np.array([30, 500, 70])
p=np.array([1000, 170, 1500])
total = np.dot(f, p.T)
print(total, '원')

220000 원


In [25]:
# 가중치 평균
a = np.array([87, 93, 90, 100])
b = np.array([88, 92, 93, 85])
w = np.array([4, 4, 4, 1]) #가중치
print(a@w.T/np.sum(w), b@w.T/np.sum(w))

90.76923076923077 90.53846153846153


In [29]:
s = np.array([[87, 93, 90, 100], [88, 92, 93, 85]])
w = np.array([4, 4, 4, 1]).reshape(-1, 1)
s @ w / np.sum(w)

array([[90.76923077],
       [90.53846154]])

### 유사도 검사
- 두 벡터가 비슷할수록 높은 점수가 나옴
- cosine similarity 사용 가능

In [30]:
v1 = np.array([1, 1, 1, 1, 0])
v2 = np.array([1, 1, 1, 0, 0])
v3 = np.array([1, 0, 0, 0, 0])
print(v1 @ v2.T)
print(v1 @ v3.T)

3
1


## 주요 함수
- np.min() : 최솟값
- np.max() : 최댓값
- np.argmin() 
- np.argmax()
- np.sum() : 합계
- np.mean() : 평균
- np.median() : 중앙값
- np.var, np.std(): 작을 수록 평균값에 뭉쳐있음
- np.random.normal() : 정규 분포 자료 생성
- np.random.shuffle(): 아이템의 순서를 뒤섞음

### shuffle : 아이템의 순서를 뒤섞음
- np.random.shuffle(ar)

In [31]:
a = np.arange(1, 101)
np.random.shuffle(a)
a = a.reshape(10, 10)
a

array([[ 58,  12,  92,   5,  64,  91,  14,  53,  40,  78],
       [  9,  76,  48,  90,  41,  42,  66,  10,  26,  25],
       [ 63,  83,  52,  13,  75,  23,  80,  94,  72,  20],
       [ 19,  45,  70,  74,  22,  65,  39,  99,  93,  30],
       [  7,  79,  60,  71,  17,  51,  44,  87,  97,  81],
       [  3,  11,  31,  15,  29,  18, 100,  47,  86,  98],
       [ 28,  54,  36,  82,  35,  55,   8,  68,  95,   4],
       [ 77,  49,  38,  32,  56,  37,  62,  46,   6,  69],
       [ 61,  85,  59,  27,  89,  84,  21,   2,  73,   1],
       [ 96,  43,  33,  24,  16,  57,  67,  50,  88,  34]])

In [35]:
np.max(a)

100

In [38]:
np.argmax(a) #최댓값 100의 위치를 찾음

56

In [49]:
np.max(a, axis = 1) #각 행의 최대값 출력      #1번 축(가로) 기준으로, 0(세로)

array([ 92,  90,  94,  99,  97, 100,  95,  77,  89,  96])

In [41]:
np.argmax(a, axis = 1) #최댓값의(각 행의) 위치 인덱스

array([2, 3, 7, 7, 8, 6, 8, 0, 4, 0], dtype=int64)

In [42]:
ar = np.arange(1, 31, 2).reshape(3, 5)
ar

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [47]:
np.sum(ar), np.mean(ar), np.median(ar) #전체합, 평균, 중간값

(225, 15.0, 15.0)

In [46]:
np.sum(ar, axis = 0) #0번 축이 세로

array([33, 39, 45, 51, 57])

In [48]:
np.sum(ar, axis = 1) #1번 축이 가로

array([ 25,  75, 125])

In [51]:
np.sum(ar[1:], axis = 0) #ar[1:, :] 생략

array([32, 36, 40, 44, 48])

In [52]:
#객체지향화 가능
ar.sum(axis = 0) #세로

array([33, 39, 45, 51, 57])

In [53]:
ar.sum(axis = 1) #가로

array([ 25,  75, 125])

In [55]:
ar.mean()

15.0

In [56]:
ar.mean(axis = 0)

array([11., 13., 15., 17., 19.])

In [60]:
#median은 객체지향화X
#ar.median() #오류발생

In [58]:
np.median(ar)

15.0

In [59]:
np.median(ar, axis = 1)

array([ 5., 15., 25.])

## 정규 분포
- 평균 100, 표준편차 15인 실수값 100000개의 원소를 가지는 정규분포 배열을 생성하시오.  최대값, 최소값, 평균, 표준편차를 구하시오.
- (평균 – 표준편차) ~ (평균 + 표준편차) 구간에는 몇 %의 자료가 포함되어 있는가?
- (평균 – 2*표준편차) ~ (평균 + 2*표준편차) 구간에는 몇 %의 자료가 포함되어 있는가?


### np.random.normal (정규 분포 자료 생성)
- np.random.normal(loc = 0.0, scale = 1.0, size = None)
- loc = 평균값, scale = 표준편차, size = 생성하는 자료의 수

In [66]:
A = np.random.normal(loc = 100, scale = 15, size = 100000)
B = A.copy()
np.max(A), np.mean(A), np.min(A), np.std(A)

(166.5004033563532, 99.9760184397903, 35.73252174166575, 14.944192609704434)

In [67]:
#(평균 - 표준편차 = 85) ~(평균 + 표준편차 = 115) 구간에 몇%의 자료가 포함되어 있는가?
A[A < 85] = 0
A[A > 115] = 0
A[A > 0] = 1
print(np.sum(A)) #구간에 있는 자료의 개수
print(np.sum(A) / 100000 * 100, "%") #print(str(np.sum(A) / 100000 * 100 + "%")

68569.0
68.569 %


In [71]:
#(평균 - 2*표준편차 = 70) ~(평균 + 2*표준편차 = 130) 구간에 몇%의 자료가 포함되어 있는가?
A = B.copy()
A[A < 70] = 0
A[A > 130] = 0
A[A > 0] = 1
print(np.sum(A)) #구간에 있는 자료의 개수
print(np.sum(A) / 100000 * 100, "%")

95434.0
95.434 %


### sort

In [72]:
ar = np.arange(1, 16)
np.random.shuffle(ar)
ar = ar.reshape(3, 5)
ar

array([[14,  6,  5,  3,  9],
       [15,  4, 13, 11,  8],
       [12,  1,  7,  2, 10]])

In [73]:
ar2 = np.sort(ar) #axis = -1이 기본
ar2

array([[ 3,  5,  6,  9, 14],
       [ 4,  8, 11, 13, 15],
       [ 1,  2,  7, 10, 12]])

In [75]:
ar3 = np.sort(ar, axis = 0)
ar3

array([[12,  1,  5,  2,  8],
       [14,  4,  7,  3,  9],
       [15,  6, 13, 11, 10]])

### sqrt

In [77]:
A = np.arange(1, 17)
np.sqrt(A) #제곱근 중 양수만 반환

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        ])

In [78]:
x = np.arange(10).reshape(2, 5)
y = np.copy(x) #x.copy()와 동일
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
y[0][0] = 10
y

array([[10,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [82]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 파일 입출력
- savetxt: 텍스트 파일로 저장
- loadtxt: 텍스트 파일에서 자료 읽기

In [83]:
a

array([[ 58,  12,  92,   5,  64,  91,  14,  53,  40,  78],
       [  9,  76,  48,  90,  41,  42,  66,  10,  26,  25],
       [ 63,  83,  52,  13,  75,  23,  80,  94,  72,  20],
       [ 19,  45,  70,  74,  22,  65,  39,  99,  93,  30],
       [  7,  79,  60,  71,  17,  51,  44,  87,  97,  81],
       [  3,  11,  31,  15,  29,  18, 100,  47,  86,  98],
       [ 28,  54,  36,  82,  35,  55,   8,  68,  95,   4],
       [ 77,  49,  38,  32,  56,  37,  62,  46,   6,  69],
       [ 61,  85,  59,  27,  89,  84,  21,   2,  73,   1],
       [ 96,  43,  33,  24,  16,  57,  67,  50,  88,  34]])

In [84]:
np.savetxt('d:/Ai/numbers.csv', a, delimiter=',') #과학적 표기법으로 저장

In [88]:
b = np.loadtxt('d:/Ai/numbers.csv', delimiter=',')
b.shape

(10, 10)

In [89]:
b

array([[ 58.,  12.,  92.,   5.,  64.,  91.,  14.,  53.,  40.,  78.],
       [  9.,  76.,  48.,  90.,  41.,  42.,  66.,  10.,  26.,  25.],
       [ 63.,  83.,  52.,  13.,  75.,  23.,  80.,  94.,  72.,  20.],
       [ 19.,  45.,  70.,  74.,  22.,  65.,  39.,  99.,  93.,  30.],
       [  7.,  79.,  60.,  71.,  17.,  51.,  44.,  87.,  97.,  81.],
       [  3.,  11.,  31.,  15.,  29.,  18., 100.,  47.,  86.,  98.],
       [ 28.,  54.,  36.,  82.,  35.,  55.,   8.,  68.,  95.,   4.],
       [ 77.,  49.,  38.,  32.,  56.,  37.,  62.,  46.,   6.,  69.],
       [ 61.,  85.,  59.,  27.,  89.,  84.,  21.,   2.,  73.,   1.],
       [ 96.,  43.,  33.,  24.,  16.,  57.,  67.,  50.,  88.,  34.]])